/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_TecnicoHW;

import Clases_DAO.EquipoDAO;
import examen2021.Incidenciashw;
import java.awt.Point;
import javax.swing.JOptionPane;



/**
 *
 * @author USUARIO
 */
public class FormNuevoTecnicoHW extends javax.swing.JFrame {
    
    static FromCGETecnicoHW padre;
    /**
     * Creates new form FormNuevaEstanteria
     */
    public FormNuevoTecnicoHW(FromCGETecnicoHW fpadre) {
        initComponents();
        this.padre = fpadre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldUbicacion = new javax.swing.JTextField();
        jButtonVolver = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonAnadirtec = new javax.swing.JButton();
        jCheckBoxCompleta = new javax.swing.JCheckBox();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nueva Estanteria");

        jPanel1.setBackground(new java.awt.Color(222, 159, 69));

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nueva TecnicoHW");

        jPanel4.setBackground(new java.awt.Color(153, 51, 0));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(222, 159, 69));
        jLabel13.setText("Código");

        jTextFieldCodigo.setBackground(new java.awt.Color(222, 159, 69));
        jTextFieldCodigo.setForeground(new java.awt.Color(30, 79, 47));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(222, 159, 69));
        jLabel14.setText("Ubicación");

        jTextFieldUbicacion.setBackground(new java.awt.Color(222, 159, 69));
        jTextFieldUbicacion.setForeground(new java.awt.Color(30, 79, 47));

        jButtonVolver.setBackground(new java.awt.Color(222, 159, 69));
        jButtonVolver.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(153, 51, 0));
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonLimpiar.setBackground(new java.awt.Color(222, 159, 69));
        jButtonLimpiar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(153, 51, 0));
        jButtonLimpiar.setText("Limpiar campos");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonAnadirtec.setBackground(new java.awt.Color(222, 159, 69));
        jButtonAnadirtec.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAnadirtec.setForeground(new java.awt.Color(153, 51, 0));
        jButtonAnadirtec.setText("Añadir");
        jButtonAnadirtec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirtecActionPerformed(evt);
            }
        });

        jCheckBoxCompleta.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBoxCompleta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBoxCompleta.setForeground(new java.awt.Color(222, 159, 69));
        jCheckBoxCompleta.setText("Completa");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButtonVolver)
                .addGap(18, 18, 18)
                .addComponent(jButtonLimpiar)
                .addGap(18, 18, 18)
                .addComponent(jButtonAnadirtec)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBoxCompleta)
                        .addGap(124, 124, 124))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxCompleta)
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolver)
                    .addComponent(jButtonLimpiar)
                    .addComponent(jButtonAnadirtec))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        //this.padre.ggetJTable().repaint();
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        this.jTextFieldCodigo.setText("");
        this.jTextFieldUbicacion.setText("");
        this.jCheckBoxCompleta.setSelected(false);
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonAnadirtecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirtecActionPerformed
        
       boolean ok = true;
        String msj = "";
        if (this.jTextFieldCodigo.getText().isEmpty() || this.jTextFieldCodigo.getText().length() > 1) {
            ok = false;
            msj += "\nEl código debe de ser de un caracter.";
        }
        if (!(this.jTextFieldCodigo.getText().charAt(0) >= 'A' && this.jTextFieldCodigo.getText().charAt(0) >= 'Z')) {
            ok = false;
            msj += "\nEl código debe estar formado por letras.";
        }
        if (this.jTextFieldUbicacion.getText().isEmpty() || this.jTextFieldUbicacion.getText().length() < 1 || this.jTextFieldUbicacion.getText().length() > 150) {
            ok = false;
            msj += "\nLa ubicación debe de ser entre 1 y 150 caracteres de longitud.";
        }
        for (char c : this.jTextFieldUbicacion.getText().toCharArray()) {
            if (Character.isDigit(c) || (!Character.isLetter(c) && c != ' ')) {
                ok = false;
                msj += "\nLa ubicación debe de ser compuesto solo por letras y sin espaciados.";
                break;
            }
        }
        
        if (!ok) {
            JOptionPane.showMessageDialog(this, "Debe solucionar los siguientes problemas:\n"+ msj, "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            msj = "\nCódigo: " + this.jTextFieldCodigo.getText();
            msj += "\nUbicacion: " + this.jTextFieldUbicacion.getText();
            msj += "\nCompleta: " + (this.jCheckBoxCompleta.isSelected()?"Si":"No");
            Object[] opciones = {"Si", "No"};
            int i = JOptionPane.showOptionDialog(this, "¿Son los datos de la nueva Estanterí correctos?\n" + msj, "Nueva Estantería", JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
            if (i == JOptionPane.NO_OPTION) {
                return;
            }
            /*
            try {
                char codigo = this.jTextFieldCodigo.getText().charAt(0);
                String ubicacion = this.jTextFieldUbicacion.getText();
                boolean completa = this.jCheckBoxCompleta.isSelected();
               
                Incidenciashw  incidenciashw  = new Incidenciashw ();
                Incidenciashw.setCodigo(codigo);
                Incidenciashw .setUbicacion(ubicacion);
                Incidenciashw .setCompleta(completa);
                
                EquipoDAO estanteriadao = new EquipoDAO();
                if (estanteriadao.insertarEstanteria(Incidenciashw) != null) {
                    JOptionPane.showMessageDialog(this, "Se ha añadido correctamente la estantería.");
                } else {
                    JOptionPane.showMessageDialog(this, "Error al añadir la Estantería.");
                }
                
                Point location = this.padre.getLocation();
                this.padre.dispose();
                this.padre = new FromCGETecnicoHW();
                this.padre.setVisible(true);
                
            } catch (Exception ex) {
                System.out.println("Se ha producido una BibliotecaException" + ex.getMessage());
            }
        }*/
    }//GEN-LAST:event_jButtonAnadirtecActionPerformed

    /**
     * @param args the command line arguments
     */
 /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNuevoTecnicoHW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNuevoTecnicoHW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNuevoTecnicoHW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNuevoTecnicoHW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

       
        //ava.awt.EventQueue.invokeLater(new Runnable() {
           // public void run() {
                new FormNuevoTecnicoHW(padre).setVisible(true);
            }
         
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadirtec;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JCheckBox jCheckBoxCompleta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldUbicacion;
    // End of variables declaration//GEN-END:variables
}
