/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_TecnicoHW;

/**
 *
 * @author Rim
 */
public class FromCGETecnicoHW extends javax.swing.JFrame {

    /**
     * Creates new form FromCGETecnicoHW
     */
    public FromCGETecnicoHW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Tec = new javax.swing.JPanel();
        jLabel1Tec = new javax.swing.JLabel();
        jButtonNuevo2Tec = new javax.swing.JButton();
        jButtonModificarTec = new javax.swing.JButton();
        jButtonEliminarTec = new javax.swing.JButton();
        jButtonVolverTec = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTecnico = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1Tec.setBackground(new java.awt.Color(222, 159, 69));

        jLabel1Tec.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel1Tec.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1Tec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Tec.setText("Gestión de TecnicoHW");

        jButtonNuevo2Tec.setBackground(new java.awt.Color(153, 51, 0));
        jButtonNuevo2Tec.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonNuevo2Tec.setForeground(new java.awt.Color(222, 159, 69));
        jButtonNuevo2Tec.setText("Nuevo");
        jButtonNuevo2Tec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevo2TecActionPerformed(evt);
            }
        });

        jButtonModificarTec.setBackground(new java.awt.Color(153, 51, 0));
        jButtonModificarTec.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jButtonModificarTec.setForeground(new java.awt.Color(222, 159, 69));
        jButtonModificarTec.setText("Modificar");
        jButtonModificarTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarTecActionPerformed(evt);
            }
        });

        jButtonEliminarTec.setBackground(new java.awt.Color(153, 51, 0));
        jButtonEliminarTec.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jButtonEliminarTec.setForeground(new java.awt.Color(222, 159, 69));
        jButtonEliminarTec.setText("Eliminar");
        jButtonEliminarTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarTecActionPerformed(evt);
            }
        });

        jButtonVolverTec.setBackground(new java.awt.Color(153, 51, 0));
        jButtonVolverTec.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonVolverTec.setForeground(new java.awt.Color(222, 159, 69));
        jButtonVolverTec.setText("Volver");
        jButtonVolverTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverTecActionPerformed(evt);
            }
        });

        jTableTecnico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableTecnico);

        javax.swing.GroupLayout jPanel1TecLayout = new javax.swing.GroupLayout(jPanel1Tec);
        jPanel1Tec.setLayout(jPanel1TecLayout);
        jPanel1TecLayout.setHorizontalGroup(
            jPanel1TecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1Tec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1TecLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButtonNuevo2Tec, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonModificarTec, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarTec, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVolverTec, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1TecLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        jPanel1TecLayout.setVerticalGroup(
            jPanel1TecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1TecLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1Tec)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1TecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolverTec, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNuevo2Tec, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificarTec, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarTec, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1Tec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1Tec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevo2TecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevo2TecActionPerformed
         FormNuevoTecnicoHW nuevaestanteria = new  FormNuevoTecnicoHW (this);
        nuevaestanteria.setVisible(true);
    }//GEN-LAST:event_jButtonNuevo2TecActionPerformed

    private void jButtonModificarTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarTecActionPerformed
       /* if (this.jTableTecnico.getSelectedRowCount() == 0 || this.jTableTecnico.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(this, "Para modificar debe seleccionar una única Estanteria de la tabla");
        } else {
            int filaSelecc = jTableTecnico.getSelectedRow();
            int id = Integer.valueOf(jTableTecnico.getModel().getValueAt(filaSelecc, 0).toString());
            char cod = jTableTecnico.getModel().getValueAt(filaSelecc, 1).toString().charAt(0);
            String ubi = jTableTecnico.getModel().getValueAt(filaSelecc, 2).toString();
            boolean com = Boolean.valueOf(jTableTecnico.getModel().getValueAt(filaSelecc, 3).toString());
            Estanteria seleccionado = new Estanteria (id, cod, ubi, com);

            FormModificarEstanteria modifEstanteria = new FormModificarEstanteria(this, seleccionado);
            modifEstanteria.setVisible(true);
       */
        
    }//GEN-LAST:event_jButtonModificarTecActionPerformed

    private void jButtonEliminarTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarTecActionPerformed
        /*if (this.jTableTecnico.getSelectedRowCount() == 0 || this.jTableTecnico.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(this, "Para eliminar debe seleccionar una única Estanteria de la tabla");
        } else {
            int filaSelecc = jTableTecnico.getSelectedRow();
            int id = Integer.valueOf(jTableTecnico.getModel().getValueAt(filaSelecc, 0).toString());
            char cod = jTableTecnico.getModel().getValueAt(filaSelecc, 1).toString().charAt(0);
            String ubi = jTableTecnico.getModel().getValueAt(filaSelecc, 2).toString();
            boolean com = Boolean.valueOf(jTableTecnico.getModel().getValueAt(filaSelecc, 3).toString());
            Estanteria seleccionado = new Estanteria (id, cod, ubi, com);

            FormEliminarEstanteria elimEstanteria = new FormEliminarEstanteria(this, seleccionado);
            elimEstanteria.setVisible(true);
        }*/
    }//GEN-LAST:event_jButtonEliminarTecActionPerformed

    private void jButtonVolverTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverTecActionPerformed
        this.dispose();
       // MenuPrincipalB.main(null);
    }//GEN-LAST:event_jButtonVolverTecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromCGETecnicoHW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromCGETecnicoHW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromCGETecnicoHW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromCGETecnicoHW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromCGETecnicoHW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminarTec;
    private javax.swing.JButton jButtonModificarTec;
    private javax.swing.JButton jButtonNuevo2Tec;
    private javax.swing.JButton jButtonVolverTec;
    private javax.swing.JLabel jLabel1Tec;
    private javax.swing.JPanel jPanel1Tec;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTecnico;
    // End of variables declaration//GEN-END:variables
}
