/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_TecnicoHW;



/**
 *
 * @author Rim
 */
public class FromModificarTecnicoHw extends javax.swing.JFrame {
    static FromCGETecnicoHW padre;
    //static Incidenciahw ev;
    //private JDatePickerImpl datePickerFechaHora;

    /**
     * Creates new form FromModificarEvento
     */
   /* public FromModificarTecnicoHw(FromGESEvento fpadre, Evento ev) {
        initComponents();
        this.padre = fpadre;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListPlantas = new javax.swing.JList<>();
        checkbox1 = new java.awt.Checkbox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2Evento = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldNombreEvento = new javax.swing.JTextField();
        jTextFieldIDEvento = new javax.swing.JTextField();
        jTextFieldFechaEvento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonModificarEvento = new javax.swing.JButton();
        jButtonLimpiarCamposEvento = new javax.swing.JButton();
        jButtonVolverEvento = new javax.swing.JButton();

        jListPlantas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListPlantas);

        checkbox1.setLabel("checkbox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("        Modificar TecnicoHW                       ");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setMaximumSize(new java.awt.Dimension(223, 23));
        jLabel1.setMinimumSize(new java.awt.Dimension(233, 23));
        jLabel1.setPreferredSize(new java.awt.Dimension(223, 23));

        jPanel2Evento.setBackground(new java.awt.Color(255, 204, 204));

        jLabelNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNombre.setText("Nombre");

        jLabelID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelID.setText("ID");

        jLabelTelefono.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelTelefono.setText("Fecha");

        jTextFieldNombreEvento.setBackground(new java.awt.Color(143, 207, 159));
        jTextFieldNombreEvento.setForeground(new java.awt.Color(30, 79, 47));

        jTextFieldIDEvento.setBackground(new java.awt.Color(143, 207, 159));
        jTextFieldIDEvento.setForeground(new java.awt.Color(30, 79, 47));

        jTextFieldFechaEvento.setBackground(new java.awt.Color(143, 207, 159));
        jTextFieldFechaEvento.setForeground(new java.awt.Color(30, 79, 47));
        jTextFieldFechaEvento.setText("FECHA");

        jLabel3.setBackground(new java.awt.Color(255, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Para modificar pulse botón modificar");

        jButtonModificarEvento.setBackground(new java.awt.Color(255, 102, 204));
        jButtonModificarEvento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonModificarEvento.setForeground(new java.awt.Color(30, 79, 47));
        jButtonModificarEvento.setText("Modificar");
        jButtonModificarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarEventoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2EventoLayout = new javax.swing.GroupLayout(jPanel2Evento);
        jPanel2Evento.setLayout(jPanel2EventoLayout);
        jPanel2EventoLayout.setHorizontalGroup(
            jPanel2EventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2EventoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModificarEvento)
                .addGap(26, 26, 26))
            .addGroup(jPanel2EventoLayout.createSequentialGroup()
                .addGroup(jPanel2EventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2EventoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelNombre)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNombreEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2EventoLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2EventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2EventoLayout.createSequentialGroup()
                                .addComponent(jLabelTelefono)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2EventoLayout.createSequentialGroup()
                                .addComponent(jLabelID)
                                .addGap(47, 47, 47)
                                .addComponent(jTextFieldIDEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2EventoLayout.setVerticalGroup(
            jPanel2EventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2EventoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2EventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jButtonModificarEvento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel2EventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombreEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2EventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID)
                    .addComponent(jTextFieldIDEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2EventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefono))
                .addGap(82, 82, 82))
        );

        jButtonLimpiarCamposEvento.setBackground(new java.awt.Color(255, 102, 204));
        jButtonLimpiarCamposEvento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonLimpiarCamposEvento.setForeground(new java.awt.Color(30, 79, 47));
        jButtonLimpiarCamposEvento.setText("Limpiar campos");
        jButtonLimpiarCamposEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarCamposEventoActionPerformed(evt);
            }
        });

        jButtonVolverEvento.setBackground(new java.awt.Color(255, 102, 204));
        jButtonVolverEvento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonVolverEvento.setForeground(new java.awt.Color(30, 79, 47));
        jButtonVolverEvento.setText("Volver");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel2Evento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButtonVolverEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimpiarCamposEvento)))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanel2Evento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButtonLimpiarCamposEvento)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(403, Short.MAX_VALUE)
                .addComponent(jButtonVolverEvento)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarCamposEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarCamposEventoActionPerformed
        this.jTextFieldNombreEvento.setText("");
        this.jTextFieldIDEvento.setText("");
        this.jTextFieldFechaEvento.setText("");
    }//GEN-LAST:event_jButtonLimpiarCamposEventoActionPerformed

    private void jButtonModificarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarEventoActionPerformed
        boolean ok = true;
        String msj = "";
        if (this.jTextFieldNombreEvento.getText().isEmpty()) {
            ok = false;
            msj += "\n El NOMBRE es obligatorio";
        }
        if (this.jTextFieldIDEvento.getText().isEmpty()) {
            ok = false;
                msj += "\n El ID es obligatorio";
        }
        if (this.jTextFieldFechaEvento.getText().isEmpty()) {
            ok = false;
            msj += "\nLa fecha de plantación es obligatoria.";
        }
       
        else {
            try {

            } catch (Exception e) {
                ok = false;
                msj += "\n El formato para el id es inválido";
                System.out.println(e.getMessage());
            }
        }

        /*if (!ok) {
            JOptionPane.showMessageDialog(this, "Debe solucionar los siguientes problemas: \n" + msj, "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            msj = " \nNombre: " + this.jTextFieldNombreEvento.getText();
            msj += "\nID: " + this.jTextFieldIDEvento.getText();
             msj += "\nID: " + this.jTextFieldFechaEvento.getText();
     

            Object [] options = {"Sí", "No"};

            int i = JOptionPane.showOptionDialog(this, "Desea introducir estos datos para modificar el Evento?\n" + msj, "Modificar Evento", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,null ,options, options[0]);
            if (i == JOptionPane.NO_OPTION) {
                return;
            }
            try {
                String nombre = this.jTextFieldNombreEvento.getText();
                String ID = this.jTextFieldIDEvento.getText();
                String Fecha = this.jTextFieldFechaEvento.getText();
                  //String fechaEvenStr = this.datePickerFechaHora.getJFormattedTextField().getText();
                //DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                
                //Date fechaHora = java.sql.Date.valueOf(LocalDate.parse(fechaEvenStr, dateFormatter));
                
               // this.ev.setFechaHora(fechaHora);
                
                 Evento evento = new Evento();
                 evento.setNombre(nombre);
                
               EventoDAO eventodao = new EventoDAO();
                if (eventodao.insertarEvento(evento) !=null) {
                    JOptionPane.showMessageDialog(this, "Se ha modificado el Evento correctamente");
                } else {
                    JOptionPane.showMessageDialog(this, "Error al modificar el Evento");
                }
                
                Point location = this.padre.getLocation();
                this.padre.dispose();
                this.padre = new FromGESEvento();
                this.padre.setVisible(true);
                        
                
            } catch (BibliotecaException ex) {
                System.out.println("Se ha producido una BibliotecaException" + ex.getMessage());
            }
    }                        
    }//GEN-LAST:event_jButtonModificarEventoActionPerformed

    /**
     * @param args the command line arguments
     */
 /*   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromModificarTecnicoHw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromModificarTecnicoHw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromModificarTecnicoHw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromModificarTecnicoHw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(new Runnable() {
           // public void run() {
            //    new FromModificarTecnicoHw(padre, ev).setVisible(true);
            //}
    // });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkbox1;
    private javax.swing.JButton jButtonLimpiarCamposEvento;
    private javax.swing.JButton jButtonModificarEvento;
    private javax.swing.JButton jButtonVolverEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JList<String> jListPlantas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2Evento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldFechaEvento;
    private javax.swing.JTextField jTextFieldIDEvento;
    private javax.swing.JTextField jTextFieldNombreEvento;
    // End of variables declaration//GEN-END:variables
}
