/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entidades;

import Clases_DAO.CategoriaDAO;
import java.awt.Point;
import javax.swing.JOptionPane;

/**
 *
 * @author Rim
 */
public class FormModificarCategoria extends javax.swing.JFrame {

    static Gestion_Categorias padre;
    static Categoria categoria;

    /**
     * Creates new form FormModificarCategoria
     */
    public FormModificarCategoria(Gestion_Categorias fpadre, Categoria c) {
        initComponents();
        this.padre = fpadre;
        this.categoria = c;
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Examen_PROGRAMACIONPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("Examen_PROGRAMACIONPU").createEntityManager();
        categoriaQuery = java.beans.Beans.isDesignTime() ? null : Examen_PROGRAMACIONPUEntityManager.createQuery("SELECT c FROM Categoria c");
        categoriaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : categoriaQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2categoria = new javax.swing.JLabel();
        jTextField1CategoriaTxt = new javax.swing.JTextField();
        jButton1borrar$ = new javax.swing.JButton();
        jButton2volver = new javax.swing.JButton();
        jButton3Modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Modificar Categoria");

        jLabel2categoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2categoria.setText("Categoria");

        jTextField1CategoriaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1CategoriaTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2categoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1CategoriaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1CategoriaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2categoria))
                .addGap(58, 58, 58))
        );

        jButton1borrar$.setText("Borrar Campos");
        jButton1borrar$.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1borrar$ActionPerformed(evt);
            }
        });

        jButton2volver.setText("Volver");
        jButton2volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2volverActionPerformed(evt);
            }
        });

        jButton3Modificar.setText("Modificar");
        jButton3Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2volver, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1borrar$, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1borrar$)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2volver)
                    .addComponent(jButton3Modificar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1borrar$ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1borrar$ActionPerformed
        // TODO add your handling code here:
        this.jTextField1CategoriaTxt.setText("");
    }//GEN-LAST:event_jButton1borrar$ActionPerformed

    private void jTextField1CategoriaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1CategoriaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1CategoriaTxtActionPerformed

    private void jButton3ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ModificarActionPerformed
        boolean ok = true;
        String msj = "";
        if (this.jTextField1CategoriaTxt.getText().isEmpty()) {
            ok = false;
            msj += "\n El Categoria es obligatorio";
        } else {
            try {

            } catch (Exception e) {
                ok = false;
                msj += "\n El formato para el Categoria es inválido";
                System.out.println(e.getMessage());
            }
        }

        if (!ok) {
            JOptionPane.showMessageDialog(this, "Debe solucionar los siguientes problemas: \n" + msj, "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            msj = " \nCategoria: " + this.jTextField1CategoriaTxt.getText();

            Object[] options = {"Sí", "No"};

            int i = JOptionPane.showOptionDialog(this, "Desea introducir estos datos para modificar el Categoria?\n" + msj, "Modificar Categoria", JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if (i == JOptionPane.NO_OPTION) {
                return;
            }
            try {
                String categ = this.jTextField1CategoriaTxt.getText();

                Categoria categoria = new Categoria();
                categoria.setCategoria(categ);

                CategoriaDAO categoriaDAO = new CategoriaDAO();
                if (CategoriaDAO.insertarCategoria(categoria) != null) {
                    JOptionPane.showMessageDialog(this, "Se ha modificado el Categoria correctamente");
                } else {
                    JOptionPane.showMessageDialog(this, "Error al modificar el Categoria");
                }

                Point location = this.padre.getLocation();
                this.padre.dispose();
                this.padre = new Gestion_Categorias();
                this.padre.setVisible(true);
   
           } catch (Exception e) {
                System.out.println("Se ha producido una ConcursoException" + e.getMessage());
            }
   
    }//GEN-LAST:event_jButton3ModificarActionPerformed
    }
    private void jButton2volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2volverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Gestion_Categorias.main(null);
    }//GEN-LAST:event_jButton2volverActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormModificarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormModificarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormModificarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormModificarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormModificarCategoria(padre, categoria).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager Examen_PROGRAMACIONPUEntityManager;
    private java.util.List<entidades.Categoria> categoriaList;
    private javax.persistence.Query categoriaQuery;
    private javax.swing.JButton jButton1borrar$;
    private javax.swing.JButton jButton2volver;
    private javax.swing.JButton jButton3Modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2categoria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1CategoriaTxt;
    // End of variables declaration//GEN-END:variables
}
